name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.5.0]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'viite-luoja/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
      working-directory: ./viite-luoja

    - name: Install Playwright Chromium
      run: npx playwright install chromium
      working-directory: ./viite-luoja

    - name: Run database tests
      run: node backend/tietokanta_operaatiot.test.js --test
      working-directory: ./viite-luoja
  
    - name: Run tests
      run: npm test
      working-directory: ./viite-luoja
    
    - name: Run E2E tests  
      run: npx playwright test
      working-directory: ./viite-luoja
      
    - name: Lint
      run: npx eslint src/ backend/
      working-directory: ./viite-luoja
